### ISSUE TITLE
LegionBoard Parser not working

### ISSUE THREAD

**Issue by AltNico** [vertretungsplanme/substitution-schedule-parser#16]
Currently, the substitution plan for the LOG Bruchköbel in the mobile app is empty although there are changes on the website available. I haven't done any research yet but I think the parser is broken.

Heart hasn't changed since last working time.

**Comment by johan12345** [comment]
The only change that is on the site (or at least the only one the parser detects) is "Herbstferien", and it is not assigned to any class. That is probably the reason why it does not show up. Should we instead assign it to all classes if there is no course set in LegionBoard?

**Comment by AltNico** [comment]
1. In Eye are two changes (one assigned to a teacher), maybe the date selection is not equal in the parser and Eye. But at least tomorrow it should show two changes.
2. So there's no possibility to leave both fields empty? Then I would assign it to the class/teacher "-", rather than "all".
3. OT: Why is this an enhancement? I would rather label it as a bug.

Thank you for your quick reply :)

**Comment by johan12345** [comment]
1. Then there seems to be a bug somewhere. Could you test it by running the parser locally? I'm quite busy currently because the new semester at university has started again...
2. If I recall correctly, the app currently only shows changes that have a class assigned (at least if you have a student schedule selected). When you assign the class to "-", it would of course not be shown if you have set the app to filter by a class. Another possibility would be to display it as a message instead of a substitution.
3. Indeed, if there are more changes in Eye/Heart than the parser returns it is a bug. I first thought the problem was that the app does not show the changes without any class assigned.

**Comment by AltNico** [comment]
OK, I will investigate in this case. Messages seems a good option for it. Good luck at Uni :P

**Comment by AltNico** [comment]
It gets even more curious. Note that no changes are shown in the Android client.

To conclude, in the sample the first change with no teacher and class is shown but the second change with a teacher is hidden.

# JSON requested by Eye and parser

```
[

    {
        "id": "293",
        "startingDate": "2016-10-17",
        "startingHour": "",
        "endingDate": "2016-10-29",
        "endingHour": "",
        "type": "0",
        "course": "0",
        "teacher": "0",
        "coveringTeacher": "0",
        "text": "Herbstferien",
        "reason": "-",
        "privateText": "-",
        "added": "-",
        "edited": "-"
    },
    {
        "id": "412",
        "startingDate": "2016-11-02",
        "startingHour": "",
        "endingDate": "2016-11-03",
        "endingHour": "",
        "type": "0",
        "course": "0",
        "teacher": "24",
        "coveringTeacher": "0",
        "text": "",
        "reason": "-",
        "privateText": "-",
        "added": "-",
        "edited": "-"
    }

]
```

# Output in Eye
1. Lehrer: -
   Start: Mo, 17.10.16
   Ende: Sa, 29.10.16
   Typ: Ausfall
   Text: Herbstferien
2. Lehrer: Mustermann
   Start: Mi, 2.11.16
   Ende: Do, 3.11.16
   Typ: Ausfall
   Text: -

# Excepted output in sample

## Mittwoch, 26.10.2016

last change: null

null [] Entfall Herbstferien

## Donnerstag, 27.10.2016

last change: null

null [] Entfall Herbstferien

## Freitag, 28.10.2016

last change: null

null [] Entfall Herbstferien

## Samstag, 29.10.2016

last change: null

null [] Entfall Herbstferien

## Mittwoch, 02.11.2016

last change: null

null [] Entfall Mustermann

## Donnerstag, 03.11.2016

last change: null

null [] Entfall Mustermann

# Experienced output in sample

## Mittwoch, 26.10.2016

last change: null

null [] Entfall Herbstferien

## Donnerstag, 27.10.2016

last change: null

null [] Entfall Herbstferien

## Freitag, 28.10.2016

last change: null

null [] Entfall Herbstferien

## Samstag, 29.10.2016

last change: null

null [] Entfall Herbstferien

**Comment by AltNico** [comment]
OK, I could fix the problem in the parser with #17. I think, this change will now appear in the Android client when you update the server.

However, this does not fix the main point of this issue. I guess you have to modify the client to handle changes with no classes/teachers. Can I report this issue anywhere? Then this can get closed.

**Comment by AltNico** [comment]
1. In Eye are two changes (one assigned to a teacher), maybe the date selection is not equal in the parser and Eye. But at least tomorrow it should show two changes.
2. So there's no possibility to leave both fields empty? Then I would assign it to the class/teacher "-", rather than "all".
3. OT: Why is this an enhancement? I would rather label it as a bug.

Thank you for your quick reply :)

**Comment by johan12345** [comment]
I could modify the client to show changes without classes/teachers, but from the logical standpoint, I don't think that makes sense: If a change does not apply to any teacher or class, it should not be shown.

I think the best way would be to modify the LegionBoard parser to convert changes to messages if they have no classes and no teachers assigned.

**Comment by AltNico** [comment]
@johan12345 I opened an issue for that: #18.
