### ISSUE TITLE
Substitutions with multiple teachers

### ISSUE THREAD

**Issue by johan12345** [vertretungsplanme/substitution-schedule-parser#26]
On some Untis schedules, there are substitutions concerning multiple teachers, which are then displayed as a comma-separated list. Our parser saves the whole list as a string in the `teacher` field. This means that filtering by teacher does not work for those substitutions.

**Comment by johan12345** [comment]
Internal note: notify support ticket #23106869 when done

**Comment by AltNico** [comment]
While LegionBoard Heart is only serving changes with one course/teacher, LegionBoard Eye is grouping up changes with same content excepting teachers: https://gitlab.com/legionboard/eye/blob/master/src/js/changes/show.js#L396

So, if you think about grouping changes, this would be interesting for LB too.

**Comment by johan12345** [comment]
@AltNico Yes, I think I would implement it similarly to the automatic merging of changes with the same class (https://github.com/johan12345/substitution-schedule-parser/blob/master/parser/src/main/java/me/vertretungsplan/objects/SubstitutionScheduleDay.java#L180), so it will then work for LegionBoard, too.

The only thing I wouldn't merge automatically is changes with different classes *and* teachers, but the same content otherwise, because they could as well be independent of each other.
