### ISSUE TITLE
Farbe der Titelleiste ist nicht einstellbar

### ISSUE THREAD

**Issue by dariotrombello** [vertretungsplanme/substitution-schedule-parser#57]
Egal welche Farbe eingestellt wird, ändert sich nichts.

OS: Android 8.1
Gerät: Galaxy A3 2016

**Comment by johan12345** [comment]
In diesem Projekt geht es nur um den Vertretungsplan-Parser. Fehlermeldungen zur App gerne per Mail an info@vertretungsplan.app.
